name: safe-shuttle-track

version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4:8.5
    depends_on:
      - "postgres-safe-shuttle-track-metadata"
      - "postgres-safe-shuttle-track-core"
    ports:
      - 33999:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: demirdanis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpass
  postgres-safe-shuttle-track-metadata:
    image: postgis/postgis:16-3.4
    restart: always
    volumes:
      - ./data/safe_shuttle_track_metadata_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  postgres-safe-shuttle-track-core:
    image: postgis/postgis:16-3.4
    restart: always
    volumes:
      - ./data/safe_shuttle_track_core_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - 5555:5432
  hasura:
    image: hasura/graphql-engine:v2.41.0.cli-migrations-v3
    ports:
      - "23564:23564"
      - "43172:43172"
    depends_on:
      - "postgres-safe-shuttle-track-metadata"
      - "postgres-safe-shuttle-track-core"
    restart: always
    working_dir: /app
    volumes:
      - ./safe-shuttle-track:/app
      - ./safe-shuttle-track/migrations:/hasura-migrations
      - ./safe-shuttle-track/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres-safe-shuttle-track-metadata:5432/postgres
      HASURA_GRAPHQL_SAFE_SHUTTLE_TRACK_CORE_DATABASE_URL: postgres://postgres:postgrespassword@postgres-safe-shuttle-track-core:5432/postgres
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_APIS: "graphql,metadata,pgdump"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_SERVER_PORT: 43172
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "fdcd0d88da9e7f9bb5652af0ae87323ba8cb7fcf8b6fcf9b7a034e633fbee448f41a337e8cce9d99b9d8a9cb938be39a42c0d01f89b49c42f0e34f16d7fead2d"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "naming_convention"
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: "false"
volumes:
  pgadmin_data:
