name: migrate for api gateway

on:
  push:
    tags:
      - api_gateway@*
  workflow_dispatch:

jobs:
  hasura_safe_shuttle_track_core_migration:
    name: Hasura Safe Shuttle Track Core Migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Apply hasura migrations
        uses: smplrspace/hasura-action@v3
        with:
          args: migrate apply --project safe-shuttle-track --database-name postgres-safe-shuttle-track-core
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_SECRET }}
          HASURA_WORKDIR: safe-shuttle-track
          HASURA_ENGINE_VERSION: v2.45.1
      - name: Migration OK for Safe Shuttle Track Core
        run: echo "Migration OK for Safe Shuttle Track Core"

  apply_metadata:
    name: Apply Hasura Metadata
    runs-on: ubuntu-latest
    needs: hasura_safe_shuttle_track_core_migration
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Apply Hasura metadata
        uses: smplrspace/hasura-action@v3
        with:
          args: metadata apply --project safe-shuttle-track
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_SECRET }}
          HASURA_WORKDIR: safe-shuttle-track
          HASURA_ENGINE_VERSION: v2.45.1
      - name: Metadata OK
        run: echo "Metadata OK"
